### ISSUE TITLE
Add to JuliaDiffEq and the common interface?

### ISSUE THREAD

**Issue by ChrisRackauckas** [rveltz/LSODA.jl#1]
Hey, I was wondering if you wanted to migrate this over to JuliaDiffEq. I would like to put it into the common interface so that way

```julia
solve(prob,LSODA();kwargs...)
```

will "just work" like how it currently does with OrdinaryDiffEq.jl (DifferentialEquations.jl), ODE.jl, ODEInterface.jl, and Sundials.jl. I think having LSODA as a choice would be a very nice addition to the ecosystem!

**Comment by rveltz** [comment]
Hi Chris,

After thinking a lot about this, I can see two reasons for not joining immediately. The first is I need this repository for my annual research report. 

The second reason is that this project is 'just' a wrapper, there is no Julia in it. It would be fantastic to have a native Julia version of LSODA so that it could be extended with matrix free methods for example.

Best regards,

**Comment by ChrisRackauckas** [comment]
>After thinking a lot about this, I can see two reasons for not joining immediately. The first is I need this repository for my annual research report.

I see, makes sense. Let me know when/if you consider this again. I just want to make sure this will be maintained in the future. Putting projects in orgs is a good way to distribute maintenance when authors go missing and provide help with fixing depwarns, testing, etc.

>The second reason is that this project is 'just' a wrapper, there is no Julia in it.

So is Sundials.jl.

>It would be fantastic to have a native Julia version of LSODA so that it could be extended with matrix free methods for example.

I don't know how truly useful that will be. LSODA's stiffness switching style seems too costly in most cases to be beneficial. But now that it's part of the common interface (once @sdwfrost helps with the timestepping issue), benchmarking versus all other algorithms will be trivial and so it will be easier to see whether this would be worthwhile. My guess is it won't be, but hey, that's why we benchmark 👍 .

**Comment by ChrisRackauckas** [comment]
@sdwfrost how do you set LSODA to give you the result of each timestep?

**Comment by sdwfrost** [comment]
Hi @ChrisRackauckas ; don't know off the top of my head. The original code is [here](https://github.com/sdwfrost/liblsoda/tree/master/orig), and I haven't done a great deal with it yet. I have to examine a PhD over the next couple of days, but back to work on this after that.

**Comment by ChrisRackauckas** [comment]
I found how to do this and it's in #8.
