### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by ChrisRackauckas** [rveltz/LSODA.jl#11]
As mentioned in #8, could the package have a tag after that merged? This is enough of the common interface that I would like to add LSODA.jl to the JuliaDiffEq website and start benchmarking it against the other methods. Of course, the release would need this behavior before I'd do that.

**Comment by rveltz** [comment]
Yes, I tried. I just tagged it with `git tag -a v0.0.1` and pushed the change but nothing appear in github.

**Comment by ChrisRackauckas** [comment]
Yeah, I just noticed that @sdwfrost 's registration never went through, so I gave him some pointers there.

https://github.com/JuliaLang/METADATA.jl/pull/7252

**Comment by sdwfrost** [comment]
Hi @ChrisRackauckas Can't deal with this for the next few days. Is there a simple way to merge the changes in the PR into local METADATA, update the sha etc.?

**Comment by ChrisRackauckas** [comment]
Yes, if you update the branch for your PR then it will instantly show up. So if you just add another tag then you won't need another PR. But since there's no pushed tag to this repo, the easiest thing may be to change the tag first.

Or if you're willing to give commit privileges I'd be willing to handle the tags.

**Comment by rveltz** [comment]
Thank you for the suggestion. I sent you an invitation.

**Comment by ChrisRackauckas** [comment]
I pushed a tag v0.0.1 which matches the current master and put in a PR to METADATA here:

https://github.com/JuliaLang/METADATA.jl/pull/7266

You can follow this for any updates. It includes @sdwfrost 's fixes so the previous PR (https://github.com/JuliaLang/METADATA.jl/pull/7252) shouldn't be necessary anymore.

**Comment by ChrisRackauckas** [comment]
Also FYI, judging from your last commit message I think you may have made a local tag, but from the releases page

https://github.com/rveltz/LSODA.jl/releases

you can see that the only one that exists is the one I pushed. When you tag, you have to push it, otherwise it only exists locally. This can cause some major problems. I'd suggest deleting the local (but not the remote) tag, since having two different ones can cause problems with PkgDev in the future.

**Comment by sdwfrost** [comment]
Dear @ChrisRackauckas Thanks for doing this - catching a plane right now to examine a PhD in the Netherlands! I closed the old PR.

**Comment by rveltz** [comment]
@ChrisRackauckas For the commit fbd005792e5623c6df32a85900f9e0eedf10dfb2, I did `git tag -a v0.0.1` on my machine and pushed the changes. You want me to remove the tag on my machine?

**Comment by ChrisRackauckas** [comment]
You never did push that tag.

**Comment by rveltz** [comment]
OK then to close this issue?
