### ISSUE TITLE
Update to use v0.1.1 of liblsoda

### ISSUE THREAD

**Issue by sdwfrost** [rveltz/LSODA.jl#18]
To accommodate changes, the new release needs to use v0.1.1 of liblsoda. This is straightforward for the source build, as this just requires a minor change in deps/build.jl. However, I have to build the binaries for Windows and put them on bintray.

**Comment by ChrisRackauckas** [comment]
Quick question: how are you preparing the Windows binaries?

**Comment by rveltz** [comment]
Note that we don't need this v0.1.1 on master (see [question](https://discourse.julialang.org/t/pointer-being-freed-was-not-allocated/3131/10)) but on the branch `branch-allocations-on-C-side`. I have tested intensively this last branch and noticed no malloc. The simpler solution of (see [question](https://discourse.julialang.org/t/pointer-being-freed-was-not-allocated/3131/10)), now implemented in the master, seems to work fine but I tested it less intensively.
