### ISSUE TITLE
Fix build on Windows

### ISSUE THREAD

**Issue by sdwfrost** [rveltz/LSODA.jl#3]
Dear @rveltz 

Do you want me to put a binary of the Windows liblsoda.dll on e.g. [bintray](https://bintray.com) to fix installation on Windows? This is how Rmath.jl is handled (see [here](https://github.com/JuliaStats/Rmath.jl/blob/master/deps/build.jl)).

**Comment by sdwfrost** [comment]
Fixed liblsoda to build with MinGW and added 32- and 64-bit libraries to bintray. Corrected build.jl script to pull binaries on Windows.

**Comment by rveltz** [comment]
Excellent!
