### ISSUE TITLE
Release a patch

### ISSUE THREAD

**Issue by ChrisRackauckas** [rveltz/LSODA.jl#32]
The common interface now warns whenever some option is set but ignored, throws a good error when a mass matrix is requested in the problem, and has a few other bugfixes in there. I think that about covers it and it's a good time for a patch. Can I tag a v0.1.1 @rveltz ?

**Comment by ChrisRackauckas** [comment]
Bumping for tag?

**Comment by rveltz** [comment]
Yes you can!

**Comment by ChrisRackauckas** [comment]
Is attobot not installed?

**Comment by rveltz** [comment]
I am not aware

**Comment by ChrisRackauckas** [comment]
Could you install attobot? https://github.com/attobot/attobot

**Comment by ChrisRackauckas** [comment]
Bump

**Comment by rveltz** [comment]
I did!

**Comment by ChrisRackauckas** [comment]
Cool, it's working.
