### ISSUE TITLE
Potential interpolant issue

### ISSUE THREAD

**Issue by Patol75** [rveltz/LSODA.jl#69]
I have been working with LSODA recently using `solve_ivp` as part of SciPy's integrate module, and I have encountered an issue relative to the interpolant [(PR at SciPy)](https://github.com/scipy/scipy/pull/14552). This issue looks to me as rooting from the original implementation of LSODA. I have had a play with the present LSODA.jl using the snippet below (directly adapted from one of [SciPy's test](https://github.com/scipy/scipy/blob/70f7e1e4b0e016dce24b2454f4f29aec044473c5/scipy/integrate/_ivp/tests/test_ivp.py#L143) which I have shown can capture the error), and it seems that it yields some interpolations errors too. For example, `sol(8.44)` returns `0.4576233723195187` whereas the correct result is `0.4577006507592191`. Using the branch associated with my proposed PR in SciPy, I obtain `0.45770063`, which is basically the expected result. If I look at the `t` values selected by the solver and their associated `u` solutions, I cannot find a difference between Julia and Python.

```
using DifferentialEquations
using LSODA

function rhs!(du, u, p, t)
  du[1] = u[2] / t
  du[2] = u[2] * (u[1] + 2 * u[2] - 1) / (t * (u[1] - 1))
  nothing
end

prob = ODEProblem(rhs!, [1 / 3, 2 / 9], (5.0, 9.0))
sol = solve(prob, lsoda(), reltol = 1e-8, abstol = 1e-8)
```

**Comment by ChrisRackauckas** [comment]
The post-solution interpolation is just a Hermite fallback. The `saveat` interpolation is the one that comes from LSODA. This is because LSODA does not save its interpolation data for post-solution use.

**Comment by Patol75** [comment]
I see, thanks for that. Using `saveat` yields the right answer. May I ask if you are aware of any difference in the interpolation scheme used in the C implementation of LSODA compared to the FORTRAN one?

**Comment by ChrisRackauckas** [comment]
It should be the same. The interpolation of the Adams/BDF scheme is standard because it's part of the predictor part of the method.

**Comment by Patol75** [comment]
Thanks again. I will have another look at both the C and FORTAN implementations, compare how things are wrapped in both Python and Julia, and hopefully find out why the interpolant in SciPy is misbehaving.

**Comment by Patol75** [comment]
It is definitely a scaling problem for the highest-order derivative stored in the Nordsieck history array when the method order decreases. I am guessing that, as a result of the decrease, this term does not influence the following integration step, but it indeed introduces an error within the interpolant. I am still unsure of where this error comes from (FORTRAN or SciPy), but it has definitely nothing to do with C or Julia. Therefore, I am closing this issue. Thank you for your time and help.
