### ISSUE TITLE
Add documentation via Documenter

### ISSUE THREAD

**Issue by sdwfrost** [rveltz/LSODA.jl#7]
I've made a start on adding documentation via Documenter.jl, but I can't hook in Travis to deploy the docs as I can't access the settings of the repository (see [here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html) for details).

**Comment by rveltz** [comment]
What specific thing do I have to do from the settings panel?

**Comment by sdwfrost** [comment]
Look at the link

[https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html)

You need to have the latest LSODA installed (with the docs directory), then you need to add the keys as described in the section.

**Comment by rveltz** [comment]
OK, it should works now

**Comment by rveltz** [comment]
I mean that I added the keys.

**Comment by rveltz** [comment]
Hi, what is left to do? When I click on doc, it gives a 404...

**Comment by ChrisRackauckas** [comment]
Check Travis. The docs built but didn't push. You can see that it 404's because the pages are empty:

https://github.com/rveltz/LSODA.jl/tree/gh-pages/latest

Are you sure you added both keys?

**Comment by rveltz** [comment]
Yes I am. Should I push again to force building?

**Comment by ChrisRackauckas** [comment]
it already tried to build. Travis said it couldn't push, so it's a keys issue.

**Comment by ChrisRackauckas** [comment]
Turn debug mode on for Documenter and see what it says.

**Comment by rveltz** [comment]
One of them is working now, I had made a mistake in naming the ssh key

**Comment by ChrisRackauckas** [comment]
Then it's working. Only one of them is supposed to build the docs.

**Comment by sdwfrost** [comment]
Looks like it's building and deploying now. index.md needs to be tidied up, and docstrings added. We could also use the Julia version of documentation generation (ie not using mkdocs) - any thoughts?

**Comment by rveltz** [comment]
As for not using mkdocs, I would go for the simplest: let's stay with what we have now. It is already good that docs are provided...

**Comment by sdwfrost** [comment]
OK, although I was concerned that the Win32 build was failing. Once we get the docs done and all the builds fixed, we can release (hence generating the stable docs) and register (so one can Pkg.add).

**Comment by rveltz** [comment]
That's a good point. It would be good to get the Win32 build back

**Comment by rveltz** [comment]
Do you think the build failure comes from the Documenter?

**Comment by sdwfrost** [comment]
Might well do (which could be fixed by using the Julia-only version). May well be worth tweaking the README to force another update, as the errors look more like problems downloading packages?

**Comment by ChrisRackauckas** [comment]
It looks like the build failure on Win32 came from SymEngine which is used in the common interface tests (so only a test requirement). It looks like that error was because Conda could not find the URL, so re-running the tests may be all that's needed to fix it.

**Comment by ChrisRackauckas** [comment]
This all looks done.
